# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUTMSptvxgULyaEr0XT2sTS8pvoBpLb8
"""

# ============================================
# ПРОГНОЗИРОВАНИЕ ОТТОКА КЛИЕНТОВ TELECOM
# Курсовая работа
# ============================================

# ======================
# Импорт библиотек
# ======================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    roc_curve
)

from sklearn.model_selection import GridSearchCV

from imblearn.over_sampling import SMOTE

import shap

# ======================
# Загрузка датасета
# ======================

df = pd.read_csv('/content/sample_data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

print(df.head())

# ======================
# Предварительный анализ
# ======================

print(df.info())

print(df.describe())

print(df.isnull().sum())

# ======================
# Обработка данных
# ======================

# Удаление customerID
df.drop('customerID', axis=1, inplace=True)

# Преобразование TotalCharges
df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

# Удаление пропусков
df.dropna(inplace=True)

# Кодирование целевой переменной
df['Churn'] = df['Churn'].map({
    'Yes': 1,
    'No': 0
})

# One-Hot Encoding
df = pd.get_dummies(df, drop_first=True)

# ======================
# Нормализация данных
# ======================

scaler = StandardScaler()

numeric_features = [
    'tenure',
    'MonthlyCharges',
    'TotalCharges'
]

df[numeric_features] = scaler.fit_transform(
    df[numeric_features]
)

# ======================
# EDA
# ======================

# Распределение Churn
sns.countplot(x='Churn', data=df)

plt.title('Распределение Churn')

plt.show()

# Гистограммы
df[numeric_features].hist(
    figsize=(12, 5)
)

plt.show()

# Boxplot
sns.boxplot(x=df['MonthlyCharges'])

plt.title('Boxplot MonthlyCharges')

plt.show()

# Корреляционная матрица
plt.figure(figsize=(15, 10))

sns.heatmap(
    df.corr(),
    cmap='coolwarm'
)

plt.title('Корреляционная матрица')

plt.show()

# ======================
# Кластеризация KMeans
# ======================

features = df[
    ['tenure', 'MonthlyCharges', 'TotalCharges']
]

inertia = []

for k in range(1, 11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42
    )

    kmeans.fit(features)

    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia, marker='o')

plt.xlabel('Количество кластеров')

plt.ylabel('Inertia')

plt.title('Метод локтя')

plt.show()

# KMeans
kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

df['Cluster'] = kmeans.fit_predict(features)

# Визуализация кластеров
sns.scatterplot(
    data=df,
    x='MonthlyCharges',
    y='TotalCharges',
    hue='Cluster',
    palette='viridis'
)

plt.title('Кластеры клиентов')

plt.show()

# ======================
# PCA
# ======================

pca = PCA(n_components=2)

pca_components = pca.fit_transform(features)

pca_df = pd.DataFrame(
    pca_components,
    columns=['PC1', 'PC2']
)

sns.scatterplot(
    x='PC1',
    y='PC2',
    hue=df['Churn'],
    data=pca_df
)

plt.title('PCA Visualization')

plt.show()

# ======================
# Поиск аномалий
# ======================

iso = IsolationForest(
    contamination=0.01,
    random_state=42
)

df['Anomaly'] = iso.fit_predict(features)

print(df['Anomaly'].value_counts())

# ======================
# Разделение данных
# ======================

X = df.drop(
    ['Churn', 'Cluster', 'Anomaly'],
    axis=1
)

y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ======================
# Logistic Regression
# ======================

log_model = LogisticRegression(
    max_iter=1000
)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

# ======================
# Decision Tree
# ======================

tree_model = DecisionTreeClassifier(
    random_state=42
)

tree_model.fit(X_train, y_train)

y_pred_tree = tree_model.predict(X_test)

# ======================
# Random Forest
# ======================

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

# ======================
# Gradient Boosting
# ======================

gb_model = GradientBoostingClassifier(
    random_state=42
)

gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_test)

# ======================
# Функция оценки моделей
# ======================

def evaluate_model(name, y_test, y_pred, y_proba):

    print(f'\n{name}')

    print(classification_report(
        y_test,
        y_pred
    ))

    accuracy = accuracy_score(y_test, y_pred)

    precision = precision_score(y_test, y_pred)

    recall = recall_score(y_test, y_pred)

    f1 = f1_score(y_test, y_pred)

    roc_auc = roc_auc_score(y_test, y_proba)

    print(f'Accuracy: {accuracy:.3f}')
    print(f'Precision: {precision:.3f}')
    print(f'Recall: {recall:.3f}')
    print(f'F1-score: {f1:.3f}')
    print(f'ROC-AUC: {roc_auc:.3f}')

# ======================
# Оценка моделей
# ======================

evaluate_model(
    'Logistic Regression',
    y_test,
    y_pred_log,
    log_model.predict_proba(X_test)[:, 1]
)

evaluate_model(
    'Decision Tree',
    y_test,
    y_pred_tree,
    tree_model.predict_proba(X_test)[:, 1]
)

evaluate_model(
    'Random Forest',
    y_test,
    y_pred_rf,
    rf_model.predict_proba(X_test)[:, 1]
)

evaluate_model(
    'Gradient Boosting',
    y_test,
    y_pred_gb,
    gb_model.predict_proba(X_test)[:, 1]
)

# ======================
# Confusion Matrix
# ======================

cm = confusion_matrix(y_test, y_pred_gb)

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title('Confusion Matrix')

plt.show()

# ======================
# ROC Curve
# ======================

fpr, tpr, thresholds = roc_curve(
    y_test,
    gb_model.predict_proba(X_test)[:, 1]
)

plt.plot(fpr, tpr)

plt.xlabel('False Positive Rate')

plt.ylabel('True Positive Rate')

plt.title('ROC Curve')

plt.show()

# ======================
# Grid Search
# ======================

param_grid = {
    'n_estimators': [100, 150],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 4]
}

grid_search = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print(grid_search.best_params_)

best_model = grid_search.best_estimator_

# ======================
# SMOTE
# ======================

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(
    X_train,
    y_train
)

best_model.fit(
    X_resampled,
    y_resampled
)

y_pred_best = best_model.predict(X_test)

evaluate_model(
    'Optimized Gradient Boosting',
    y_test,
    y_pred_best,
    best_model.predict_proba(X_test)[:, 1]
)

# ======================
# Voting Classifier
# ======================

voting_model = VotingClassifier(
    estimators=[
        ('lr', LogisticRegression(max_iter=1000)),
        ('rf', RandomForestClassifier(random_state=42)),
        ('gb', GradientBoostingClassifier(random_state=42))
    ],
    voting='soft'
)

voting_model.fit(X_train, y_train)

y_pred_voting = voting_model.predict(X_test)

evaluate_model(
    'Voting Classifier',
    y_test,
    y_pred_voting,
    voting_model.predict_proba(X_test)[:, 1]
)

# ======================
# Feature Importance
# ======================

importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': best_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

plt.figure(figsize=(10, 6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=importance_df.head(10)
)

plt.title('Feature Importance')

plt.show()

# ======================
# SHAP Analysis
# ======================

explainer = shap.Explainer(best_model)

shap_values = explainer(X_test)

shap.summary_plot(
    shap_values,
    X_test
)

print('Анализ завершен успешно.')